cd /var/www/vhosts/outrageGIS.com/httpdocs/weather/make
# convert -resize 330x330 noaa.gif noaa.jpg
awk -f awk-data.sh past-obs.txt > f-obs.txt
# awk '/<td width="11%/' NewFoundGap.txt > NewFoundGap2.txt
# sed 's/\/images\/wtf/http:\/\/forecast.weather.gov\/images\/wtf/g' NewFoundGap2.txt | sed 's/<\/tr>//g' > NewFoundGapWeather.txt
# awk '/<td width="11%/' RRG.txt > RRG2.txt
# sed 's/\/images\/wtf/http:\/\/forecast.weather.gov\/images\/wtf/g' RRG2.txt | sed 's/<\/tr>//g' > RRGWeather.txt
# awk '/<td width="11%/' CaveRun.txt > CaveRun2.txt
# sed 's/\/images\/wtf/http:\/\/forecast.weather.gov\/images\/wtf/g' CaveRun2.txt | sed 's/<\/tr>//g' > CaveRunWeather.txt
# awk '/<td width="11%/' BigSouth.txt > BigSouth2.txt
# sed 's/\/images\/wtf/http:\/\/forecast.weather.gov\/images\/wtf/g' BigSouth2.txt | sed 's/<\/tr>//g' > BigSouthWeather.txt
# pcregrep -M -A 53 "<div class=\"partial-width-borderbottom point-forecast-icons\">" NewFoundGap.txt | sed 's_/images/wtf/medium/_http\:\/\/forecast.weather.gov/images/wtf/medium/_' | sed 's_width\=\"86\" height\=\"86\"_width\=\"60\" height\=\"60\"_' | sed 's_<p>__' | sed 's_<div class="partial-width-borderbottom point-forecast-icons">_<table width="100%"><tr>_' | sed 's_<div class="one-ninth-first">_<td width="11%" valign="top" class="NWSweatherTEXT">_' | sed 's_</div>_</td>_' > NewFoundGapWeather.txt
pcregrep -M -A 1 "<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">" NewFoundGap.txt | sed 's/^.*<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">/<table width="100%"><tr>/' | sed 's_<li class="forecast-tombstone"><div><p class="txt-ctr-caps">_<td width="11%" valign="top" class="NWSweatherTEXT">_g'  | sed 's_/images/wtf/medium/_http://forecast.weather.gov/images/wtf/medium/_g' | sed 's_.png"_.png" width\="60 px" height\="60 px"_g'| sed 's_</p><p class="point-forecast-icons-high">__g' | sed 's_</p><p>_<br>_g' | sed 's_</p><p class="point-forecast-icons-low">__g' | sed 's_</p></div></li>_</td>_g' | sed 's_</ul>__' | sed 's_<br>Night_ Night<br><br>_g' | sed 's_<br><br><br>_<br>_g' > NewFoundGapWeather.txt
pcregrep -M -A 1 "<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">" RRG.txt | sed 's/^.*<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">/<table width="100%"><tr>/' | sed 's_<li class="forecast-tombstone"><div><p class="txt-ctr-caps">_<td width="11%" valign="top" class="NWSweatherTEXT">_g'  | sed 's_/images/wtf/medium/_http://forecast.weather.gov/images/wtf/medium/_g' | sed 's_.png"_.png" width\="60 px" height\="60 px"_g'| sed 's_</p><p class="point-forecast-icons-high">__g' | sed 's_</p><p>_<br>_g' | sed 's_</p><p class="point-forecast-icons-low">__g' | sed 's_</p></div></li>_</td>_g' | sed 's_</ul>__' | sed 's_<br>Night_ Night<br><br>_g' | sed 's_<br><br><br>_<br>_g' > RRGWeather.txt
pcregrep -M -A 1 "<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">"  CaveRun.txt | sed 's/^.*<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">/<table width="100%"><tr>/' | sed 's_<li class="forecast-tombstone"><div><p class="txt-ctr-caps">_<td width="11%" valign="top" class="NWSweatherTEXT">_g'  | sed 's_/images/wtf/medium/_http://forecast.weather.gov/images/wtf/medium/_g' | sed 's_.png"_.png" width\="60 px" height\="60 px"_g'| sed 's_</p><p class="point-forecast-icons-high">__g' | sed 's_</p><p>_<br>_g' | sed 's_</p><p class="point-forecast-icons-low">__g' | sed 's_</p></div></li>_</td>_g' | sed 's_</ul>__' | sed 's_<br>Night_ Night<br><br>_g' | sed 's_<br><br><br>_<br>_g' > CaveRunWeather.txt
pcregrep -M -A 1 "<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">" BigSouth.txt | sed 's/^.*<ul class=\"list-unstyled\" id=\"seven-day-forecast-list\">/<table width="100%"><tr>/' | sed 's_<li class="forecast-tombstone"><div><p class="txt-ctr-caps">_<td width="11%" valign="top" class="NWSweatherTEXT">_g'  | sed 's_/images/wtf/medium/_http://forecast.weather.gov/images/wtf/medium/_g' | sed 's_.png"_.png" width\="60 px" height\="60 px"_g'| sed 's_</p><p class="point-forecast-icons-high">__g' | sed 's_</p><p>_<br>_g' | sed 's_</p><p class="point-forecast-icons-low">__g' | sed 's_</p></div></li>_</td>_g' | sed 's_</ul>__' | sed 's_<br>Night_ Night<br><br>_g' | sed 's_<br><br><br>_<br>_g' > BigSouthWeather.txt
#pcregrep -M -A 53 "<div class=\"partial-width-borderbottom point-forecast-icons\">" BigSouth.txt | sed 's_/images/wtf/medium/_/images/fcicons/_' | sed 's_.png_.jpg_' | sed 's_width\=\"86\" height\=\"86\"__' | sed 's_<p>__' | sed 's_<div class="partial-width-borderbottom point-forecast-icons">_<table width="100%"><tr>_' | sed 's_<div class="one-ninth-first">_<td width="11%" valign="top" class="NWSweatherTEXT">_' | sed 's_</div>_</td>_' > BigSouthWeather.txt
pcregrep -M -A 0 '<h3 class="panel-title">Hazardous Weather Conditions</h3>'  NewFoundGap.txt | sed 's_<div class=\"panel-heading\"><h3 class=\"panel-title\">Hazardous Weather Conditions</h3></div>__' | sed 's_id=\"anchor-hazards\">_id=\"anchor-hazards\" target=\"\_blank\">_g' | sed 's_href=\"_href=\"http://forecast.weather.gov/_g' > NewFoundGapWarnings.txt
pcregrep -M -A 0 '<h3 class="panel-title">Hazardous Weather Conditions</h3>' RRG.txt | sed 's_<div class=\"panel-heading\"><h3 class=\"panel-title\">Hazardous Weather Conditions</h3></div>__' | sed 's_id=\"anchor-hazards\">_id=\"anchor-hazards\" target=\"\_blank\">_g' | sed 's_href=\"_href=\"http://forecast.weather.gov/_g' > RRGWarnings.txt
pcregrep -M -A 0 '<h3 class="panel-title">Hazardous Weather Conditions</h3>' CaveRun.txt | sed 's_<div class=\"panel-heading\"><h3 class=\"panel-title\">Hazardous Weather Conditions</h3></div>__' | sed 's_id=\"anchor-hazards\">_id=\"anchor-hazards\" target=\"\_blank\">_g' | sed 's_href=\"_href=\"http://forecast.weather.gov/_g' > CaveRunWarnings.txt
pcregrep -M -A 0 '<h3 class="panel-title">Hazardous Weather Conditions</h3>' BigSouth.txt | sed 's_<div class=\"panel-heading\"><h3 class=\"panel-title\">Hazardous Weather Conditions</h3></div>__' | sed 's_id=\"anchor-hazards\">_id=\"anchor-hazards\" target=\"\_blank\">_g' | sed 's_href=\"_href=\"http://forecast.weather.gov/_g' > BigSouthWarnings.txt
pcregrep -M -A 0 '<h3 class="panel-title">Hazardous Weather Conditions</h3>' WestSmokies.txt | sed 's_<div class=\"panel-heading\"><h3 class=\"panel-title\">Hazardous Weather Conditions</h3></div>__' | sed 's_id=\"anchor-hazards\">_id=\"anchor-hazards\" target=\"\_blank\">_g' | sed 's_href=\"_href=\"http://forecast.weather.gov/_g' > WestSmokiesWarnings.txt

#pcregrep -Mio '(?s)<div class="hazardous-conditions">(.*?)</div>' WestSmokies.txt | sed 's_<h1>_<h5>_' | sed 's_</h1>_</h5><br>_' | pcregrep '<a href=' | sed 's_">_" target="\_blank">_g' | sed 's_href=\"_href=\"http://forecast.weather.gov/_g' > WestSmokiesWarnings.txt

